name: flutter_graphql_localization_theme_config_template
description: flutter_graphql_localization_theme_config_template project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^0.6.0+1
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  firebase_storage: ^4.0.1
  font_awesome_flutter: ^8.10.0
  graphql_flutter: ^3.1.0
  intl: ^0.16.1
  overlay_support: ^1.0.5
  shared_preferences: ^0.5.12+2
  timeago: ^2.0.27

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - assets/i18n/it.json
    - assets/i18n/en.json

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
